#Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: bluechat-prod
---
#Service DB
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: bluechat-prod
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - name: db-port
      protocol: TCP
      port: 3306
      targetPort: 3306

---

#Deploy DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  namespace: bluechat-prod
spec:
  replicas: 1
  template:
    metadata:
        name: db
        labels:
          app: db
    spec:
      containers:
      - name: bluechat-db
        image: jonfarias/bluechat-db:1
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        #volumeMounts:
        #  - mountPath: "/var/lib/mysql"
        #    name: db-disk
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: bluechat-secret
                key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
              secretKeyRef:
                name: bluechat-secret
                key: mysql-database
        - name: MYSQL_USER
          valueFrom:
              secretKeyRef:
                name: bluechat-secret
                key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
              secretKeyRef:
                name: bluechat-secret
                key: mysql-password
      #volumes:
       # - name: db-disk
        #  persistentVolumeClaim:
        #    claimName: db-k8s-pvc
  selector:
    matchLabels:
      app: db