version: 2.1
orbs:
  terraform: circleci/terraform@1.2.1
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          checkout: true
          context: terraform
          persist-workspace: true
      - terraform/validate:
          checkout: true
          context: terraform
          persist-workspace: true
      - terraform/fmt:
          checkout: true
          context: terraform
          persist-workspace: true
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
      - terraform/apply:
          checkout: true
          context: terraform
          persist-workspace: true
      - terraform/destroy:
          checkout: true
          context: terraform
          persist-workspace: true
    working_directory: ~/BlueChat-CD/terraform
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle