version: 2.1
orbs:
  terraform: circleci/terraform@3.0.1
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - terraform/install:
          terraform_version: 1.1.3
      - terraform/fmt:
          path: .
      - terraform/validate:
          path: .
    working_directory: ~/BlueChat-CD/terraform
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle