version: 2.1

jobs:
  init-plan:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true    
      - run:
          name: terraform init & plan
          command: |
            docker run $DOCKER_USER/$DOCKER_CONTAINER:$TAG terraform init 
            docker run $DOCKER_USER/$DOCKER_CONTAINER:$TAG terraform plan 

  apply:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true  
      - run:
          name: terraform
          command: |
            docker run $DOCKER_USER/$DOCKER_CONTAINER:$TAG terraform apply -auto-approve

  destroy:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true  
      - run:
          name: terraform destroy
          command: |
            docker run $DOCKER_USER/$DOCKER_CONTAINER:$TAG terraform destroy -auto-approve 

workflows:
  version: 2
  Terraform:
    jobs:
      - init-plan:
          filters:
            branches:
              only: main
      - apply:
          type: approval
          filters:
            branches:
              only: main
          requires:
            - init-plan
      - destroy:
          type: approval
          filters:
            branches:
              only: main
          requires:
            - apply
