version: 2.1

jobs:
  init-plan:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true    
      - run:
          name: terraform validate
          command: |
            docker run $DOCKER_USER/$DOCKER_CONTAINER:latest terraform validate
      - run:
          name: terraform init
          command: |
            docker run $DOCKER_USER/$DOCKER_CONTAINER:latest terraform init 
      - run:
          name: terraform plan
          command: |
            docker run $DOCKER_USER/$DOCKER_CONTAINER:latest terraform plan 

  aprove-apply:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Terraform Apply-Approval
          command: |
            echo "Approve Terraform Apply"

  apply:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true  
      - run:
          name: terraform apply
          command: |
            docker run $DOCKER_USER/$DOCKER_CONTAINER:latest terraform apply -auto-approve

  aprove-destroy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Terraform Apply-Approval
          command: |
            echo "Approve Terraform Destroy"

  destroy:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true  
      - run:
          name: terraform destroy
          command: |
            docker run $DOCKER_USER/$DOCKER_CONTAINER:latest terraform destroy -auto-approve 

workflows:
  version: 2
  Terraform:
    jobs:
      - init-plan:
          filters:
            branches:
              only: main

      - aprove-apply:
          type: approval
          filters:
            branches:
              only: main
          requires:
            - init-plan

      - apply:
          filters:
            branches:
              only: main
          requires:
            - aprove-apply

      - aprove-destroy:
          type: approval
          filters:
            branches:
              only: main
          requires:
            - apply

      - destroy:
          filters:
            branches:
              only: main
          requires:
            - aprove-destroy
