name: Create Kubernetes Cluster
on: push
jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
    - uses: actions/checkout@v2
    - name: Install Terraform
      id: install-terraform
      run: wget -O terraform.zip https://releases.hashicorp.com/terraform/1.1.3/terraform_1.1.3_linux_amd64.zip && unzip terraform.zip && chmod +x terraform && sudo mv terraform /usr/local/bin 
    - name: Install Helm
      id: install-helm
      run: wget -O helm.tgz https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz && tar -vzxf helm.tgz && chmod +x linux-amd64/helm && sudo mv linux-amd64/helm /usr/local/bin          
    - name: Apply Terraform
      id: apply-terraform
      run: sed -i "s/<project-id>/${{ secrets.PROJECT_ID }}/" backend.tf 
    - name: Terraform Init and Plan   
      id: init-terraform
      run: terraform init && terraform plan
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 

#&& terraform apply -auto-approve -var="project_id=${{ secrets.PROJECT_ID  }}"